[package]
authors = ["The Rust Project Developers"]
name = "rustdoc"
version = "0.0.0"
edition = "2018"

[lib]
name = "rustdoc"
path = "lib.rs"

[dependencies]
pulldown-cmark = { version = "0.5.3", default-features = false }
minifier = "0.0.33"
rayon = { git = "https://github.com/spastorino/rustc-rayon", branch = "latch-target-thread-rustc", package = "rustc-rayon" }
tempfile = "3"
